# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessReccord',
            new_name='AccessRecord',
        ),
    ]
